# Supabase Configuration File
# This file is used to configure your Supabase project

[api]
# Port to use for the API URL (default: 54321)
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL (default: 54322)
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[realtime]
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
ip_version = "IPv4"
# The maximum length in bytes of HTTP request headers. (default: 4096)
max_header_length = 4096

[studio]
# Port to use for Supabase Studio (default: 54323)
port = 54323
# External URL of the API server that frontend connects to (default: http://127.0.0.1)
api_url = "http://127.0.0.1"
# OpenAI API Key to use for Supabase AI.
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
# Port to use for the email testing server (default: 54324)
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://127.0.0.1:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
# refresh_token_rotation_enabled = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires refresh_token_rotation_enabled to be false.
# refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow anonymous sign-ins to your project.
enable_anonymous_sign_ins = false
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use a production-ready SMTP server
# [auth.email.smtp]
# host = "localhost"
# port = 587
# user = ""
# pass = ""
# admin_email = ""
# sender_name = ""

# Uncomment to customize SMS template
# [auth.sms.template]
# Your code is {{ .Code }}

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectURL, useful for Capacitor/mobile apps
# redirect_uri = ""
# Overrides the default auth scope
# scope = ""


